/*
 * Copyright (c) 2018 - 2021, Zaphod Consulting BV, Christine Karman
 * This project is free software: you can redistribute it and/or modify it under the terms of
 * the Apache License, Version 2.0. You can find a copy of the license at
 * http://www.apache.org/licenses/LICENSE-2.0.
 */
import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    nl:{
        home:"Home",
        letters:"Brieven",
        people:"Personen",
        locations:"Locaties",
        references:"Referenties",
        subjects:"Onderwerpen",
        admin:"Admin",
        login:"Login",
        pages:"Bladzijden",
        op_nummer:"Op nummer",
        op_datum:"Op datum",
        naar_nummer:"Ga naar nummer",
        search:"Zoek",
        previous:"Vorige",
        next:"Volgende",
        op_voornaam:"Op voornaam",
        op_achternaam:"Op achternaam",
        geboren:"Geboren",
        overleden:"Overleden",
        brieven_van:"Brieven van",
        brieven_aan:"Brieven aan",
        meer:"Meer",
        nummer:"Nummer",
        to:"Aan",
        from:"Van",
        date:"Datum",
        chapter:"Hoofdstuk",
        page:"Pagina",
        content:"Inhoud"
    },
    en:{
        home:"Home",
        letters:"Letters",
        people:"People",
        locations:"Locations",
        references:"References",
        subjects:"Subjects",
        admin:"Admin",
        login:"Login",
        pages:"Pages",
        op_nummer:"By number",
        op_datum:"By date",
        naar_nummer:"Go to number",
        search:"Search",
        vorige:"Previous",
        next:"Next",
        op_voornaam:"By first name",
        op_achternaam:"By last name",
        geboren:"Birth date",
        overleden:"Deceased",
        brieven_van:"Letters from",
        brieven_aan:"Letters to",
        meer:"More",
        nummer:"Number",
        to:"To",
        from:"From",
        date:"Date",
        chapter:"Chapter",
        page:"Page",
        content:"Content"
    },
    fr: {
        home:"Home",
        letters:"Letters",
        people:"People",
        locations:"Locations",
        references:"References",
        subjects:"Subjects",
        admin:"Admin",
        login:"Login",
        pages:"Pages",
        op_nummer:"By number",
        op_datum:"By date",
        naar_nummer:"Go to number",
        search:"Search",
        vorige:"Previous",
        next:"Next",
        op_voornaam:"By first name",
        op_achternaam:"By last name",
        geboren:"Birth date",
        overleden:"Deceased",
        brieven_van:"Letters from",
        brieven_aan:"Letters to",
        meer:"More",
        nummer:"Number",
        to:"To",
        from:"From",
        date:"Date",
        chapter:"Chapter",
        page:"Page",
        content:"Content"
    },
    de: {
        home:"Home",
        letters:"Letters",
        people:"People",
        locations:"Locations",
        references:"References",
        subjects:"Subjects",
        admin:"Admin",
        login:"Login",
        pages:"Pages",
        op_nummer:"By number",
        op_datum:"By date",
        naar_nummer:"Go to number",
        search:"Search",
        vorige:"Previous",
        next:"Next",
        op_voornaam:"By first name",
        op_achternaam:"By last name",
        geboren:"Birth date",
        overleden:"Deceased",
        brieven_van:"Letters from",
        brieven_aan:"Letters to",
        meer:"More",
        nummer:"Number",
        to:"To",
        from:"From",
        date:"Date",
        chapter:"Chapter",
        page:"Page",
        content:"Content"
    }
});
export default strings;
