/*
 * Copyright (c) 2018 - 2024, Zaphod Consulting BV, Christine Karman
 * This project is free software: you can redistribute it and/or modify it under the terms of
 * the Apache License, Version 2.0. You can find a copy of the license at
 * http://www.apache.org/licenses/LICENSE-2.0.
 */
import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    nl:{
        titel:"Het nichtje van tante Thérèse",
        home:"Home",
        letters:"Brieven",
        people:"Personen",
        locations:"Locaties",
        references:"Referenties",
        topics:"Topics",
        admin:"Admin",
        login:"Login",
        logout:"Logout",
        pages:"Verhaal",
        op_nummer:"Op nummer",
        op_datum:"Op datum",
        naar_nummer:"Ga naar nummer",
        search:"Zoek",
        previous:"Vorige",
        next:"Volgende",
        op_voornaam:"Op voornaam",
        op_achternaam:"Op achternaam",
        geboren:"Geboren",
        overleden:"Overleden",
        brieven_van:"Brieven van",
        brieven_aan:"Brieven aan",
        meer:"Meer",
        nummer:"Nummer",
        to:"Aan",
        from:"Van",
        date:"Datum",
        chapter:"Hoofdstuk",
        page:"Pagina",
        content:"Inhoud",
        sender:"Afzender",
        recipient:"Ontvanger",
        location:"Plaats",
        remarks:"Opmerkingen",
        help_title: "Navigatie",
        help:"Op de brieven pagina, klik op een briefnummer of naam voor meer info. Verder kun je meestal op een naam klikken voor meer info.Op de verhaal pagina, blader met de pijltjes bovenaan.",
        location_name: "Locatie name",
        back: "Terug",
        ok: "OK",
        uit: "uit"
    },
    en:{
        titel:"Aunt Thérèse's niece",
        home:"Home",
        letters:"Letters",
        people:"People",
        locations:"Locations",
        references:"References",
        topics:"Topics",
        admin:"Admin",
        login:"Login",
        logout:"Logout",
        pages:"Story",
        op_nummer:"By number",
        op_datum:"By date",
        naar_nummer:"Go to number",
        search:"Search",
        previous:"Previous",
        next:"Next",
        op_voornaam:"By first name",
        op_achternaam:"By last name",
        geboren:"Birth date",
        overleden:"Deceased",
        brieven_van:"Letters from",
        brieven_aan:"Letters to",
        meer:"More",
        nummer:"Number",
        to:"To",
        from:"From",
        date:"Date",
        chapter:"Chapter",
        page:"Page",
        content:"Content",
        sender:"Sender",
        recipient:"Recipient",
        location:"Location",
        remarks:"Remarks",
        help_title:"Navigation",
        help:"On the letters page, click on a letter number or a name for info. In the letter pages, you can click on any name to navigate. On the story page, browse with the arrows at the top of the page.",
        location_name: "Location name",
        back: "Back",
        ok: "OK",
        uit: "from"
    },
    fr: {
        titel:"La nièce de tante Thérèse",
        home:"Accueil",
        letters:"Lettres",
        people:"Personnes",
        locations:"Villes",
        references:"Références",
        topics:"Topics",
        admin:"Admin",
        login:"Login",
        logout:"Logout",
        pages:"Histoire",
        op_nummer:"Par nombre",
        op_datum:"Par date",
        naar_nummer:"Aller au numéro",
        search:"Rechercher",
        previous:"Précédente",
        next:"Suivante",
        op_voornaam:"Par prénom",
        op_achternaam:"Par nom de famille",
        geboren:"Date de naissance",
        overleden:"Décédé",
        brieven_van:"Lettres de",
        brieven_aan:"Lettres á",
        meer:"Plus",
        nummer:"Nombre",
        to:"À",
        from:"De",
        date:"Date",
        chapter:"Chapitre",
        page:"Page",
        content:"Contenu",
        sender:"Expéditrice",
        recipient:"Destinataire",
        location:"Ville",
        remarks:"Remarques",
        help_title:"Naviguer:",
        help:"Sur la page des lettres, cliquez sur un numéro de lettre ou un nom pour plus d'informations. Dans les pages de lettres, vous pouvez cliquer sur un nom pour naviguer.",
        location_name: "Location name",
        back: "Arrière",
        ok: "OK",
        uit: "de"
    },
    de: {
        titel:"Tante Thérèses Nichte",
        home:"Startsite",
        letters:"Briefe",
        people:"Personen",
        locations:"Orte",
        references:"Referenzen",
        topics:"Topics",
        admin:"Admin",
        login:"Login",
        logout:"Logout",
        pages:"Geschichte",
        op_nummer:"Nach Nummer",
        op_datum:"Nach Datum",
        naar_nummer:"Gehe zu Nummer",
        search:"Suchen",
        previous:"Vorherige",
        next:"Nächste",
        op_voornaam:"Nach Vorname",
        op_achternaam:"Nach Nachnamen",
        geboren:"Geburtsdatum",
        overleden:"Verstorben",
        brieven_van:"Briefe von",
        brieven_aan:"Briefe nach",
        meer:"Mehr",
        nummer:"Nummer",
        to:"An",
        from:"Von",
        date:"Datum",
        chapter:"Kapitel",
        page:"Seite",
        content:"Inhalt",
        sender:"Absender",
        recipient:"Empfanger",
        location:"Ort",
        remarks:"Bemerkungen",
        help_title:"Navigieren",
        help:"Klicken Sie auf der Briefe Liste auf eine Briefnummer oder einen Namen, um Informationen zu erhalten. Auf den Briefseiten können Sie auf einen beliebigen Namen klicken, um zu navigieren.",
        location_name: "Location name",
        back: "Zurück",
        ok: "OK",
        uit: "aus"
    }
});
export default strings;
